[default]
TITLE = "CoffeVerse"
SECRET_KEY = "chavesecreta"
SQLALCHEMY_DATABASE_URI = "mysql+pymysql://root:root@localhost/coffeverse"
SQLALCHEMY_TRACK_MODIFICATIONS = false
EXTENSIONS = [
"coffeverse.extensions.database",
"coffeverse.blueprints.views",
]